### ISSUE TITLE
Drop Spanish and Rishi Dialect as official languages

### ISSUE THREAD

**Issue by doamatto** [LLEB-ME/wiki#24]
We did discuss it some time this month or the last. There is no graceful way to drop it as an official, supported language, but it is something to be considered.

Dropping the language makes general development faster and loads smaller (less locales to store and serve). 

---
A vote is needed for this to be put in effect. A majority vote is needed to proceed. Voting will end by the end of this coming week (2022-09-25T22:00:00Z).

cc @LLEB-ME/members

**Comment by cyckl** [comment]
Agreed, I'm going to lump in Rishi Dialect along with this issue. Should be a pretty simple change since no actual content was implemented in the wiki in either language.

**Comment by cyckl** [comment]
Please ensure that the French modifications actually make sense, thanks

**Comment by doamatto** [comment]
Votes in favour: 2
Votes against: 1
Votes abstained/not cast: 4

PR #25 can be merged and, subsequently, this issue can be closed once requested changes are made.

**Comment by doamatto** [comment]
A quick reminder to get this situated @cyckl.
